name: Update

on:
  schedule:
    - cron:  '30 7 * * *'
  workflow_dispatch:
permissions:
  actions: write
jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.email "it@huconn.com"
          git config --global user.name "update bot"

      - name: Run update.py script
        run: |
          python3 update.py -d -c
      - name: Git push
        run: |
          git push origin main

      - name: Switch to dummy branch
        run: |
          git checkout -b keep-alive
      - name: Keep Alive
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          committer_username: update bot
          committer_email: it@huconn.com
